#!/usr/bin/env bash

set -e

if [ $(tmux list-sessions | awk -F ':' '{print $1}' | grep -c openvpn) -eq 1 ]; then
  tmux send-keys -t openvpn C-c
  sleep 0.1
  tmux kill-session -t openvpn
  tmux refresh-client -S
  tmux display "VPN connection killed!"
fi
