#!/usr/bin/env bash

function echo_step {
  printf $'\e[37;44m\033[1m'"$1"
  echo $'\033[0m'
}

function echo_warning {
  printf $'\e[7;49;31m\033[1m'"$1"
  echo $'\033[0m'
}

function parse_branch_name {
  type git >/dev/null 2>&1
  
  if [ "$?" -ne 0 ]; then
	  return
  fi

  # Quit if this is not a Git repo.
  branch=$(git symbolic-ref HEAD 2> /dev/null)
  if [[ -z $branch ]] ; then
	  # attempt to get short-sha-name
	  branch=":$(git rev-parse --short HEAD 2> /dev/null)"
  fi
  if [ "$?" -ne 0 ]; then
	  # this must not be a git repo
	  return
  fi

  # Clean off unnecessary information.
  echo "$branch" | egrep -o "T\d+"
}

function main {
  local points=$1 
  local arcrc=$(<~/.arcrc)
  local project_phid=$(echo $arcrc | jq '.dotfiles_env_vars.project')
  local conduit_uri=$(echo $arcrc | jq '.dotfiles_env_vars.conduit_uri' --raw-output)

  local task_id=$(parse_branch_name)

  if [[ -z $task_id ]]; then
    echo_warning "Couldnt determine the task number of the current branch"
    return
  fi

  local sprint_phid=$(get_last_milestone_phid "$project_phid")
  local column_phid=$(get_column_phid $sprint_phid "In Review")

  if [[ -z $points ]]; then
    local query="{
      \"transactions\": [
	{
	  \"type\": \"column\",
	  \"value\": [$column_phid]
	}
      ],
      \"objectIdentifier\": \"$task_id\"
    }"
  else
    local query="{
      \"transactions\": [
	{
	  \"type\": \"column\",
	  \"value\": [$column_phid]
	},
	{
	  \"type\": \"points\",
	  \"value\": $points
	}
      ],
      \"objectIdentifier\": \"$task_id\"
    }"  
  fi

  local result=$(echo $query | arc call-conduit --conduit-uri $conduit_uri maniphest.edit)
  echo_step "Successfully moved task $task_id to In Review"
}

main "$1"
