#!/usr/bin/env bash

file_path="$(echo $1 | cut -d':' -f1)"
spec="$1"

if ! [ -f $file_path ]; then
  echo "File does not exist"
  exit 1
fi

cucumber_command='bin/cucumber' 
rspec_command='bin/rspec --color' 

if [[ $file_path == *.feature ]]; then
  $cucumber_command $spec
elif [[ $file_path == *_spec.rb ]]; then
  # FIVEMAT_PROFILE=1 $rspec_command $spec --format Fivemat
  $rspec_command $spec 
else
  echo "Invalid spec file given."
  exit 1
fi
