#!/usr/bin/env bash

function echo_step {
  printf $'\e[37;44m\033[1m'"$1"
  echo $'\033[0m'
}

main() {
  echo_step "NOTE: fetching raw diff for diff: $1"

  # NOTE: read conduit uri from ~/.arcrc
  local arcrc=$(<~/.arcrc)
  local conduit_uri=$(echo $arcrc | jq '.dotfiles_env_vars.conduit_uri' --raw-output)

  # NOTE: Obtain the phid for the given diff
  phid_lookup_json="$(
    echo '{
      "names": [
        "'"$1"'"
      ]
    }' | arc call-conduit --conduit-uri $conduit_uri phid.lookup
  )"

  diff_title=$(echo $phid_lookup_json | jq ".response.$1.fullName" --raw-output)
  diff_url=$(echo $phid_lookup_json | jq ".response.$1.uri" --raw-output)
  diff_phid=$(echo $phid_lookup_json | jq ".response.$1.phid" --raw-output)

  dir="`git rev-parse --git-dir`"
  mkdir -p "$dir/diffs"
  tmpfile="$dir/diffs/$1.patch"

  trap "rm -f '$tmpfile'" EXIT

  # NOTE: Print metadata to file
  echo "# =========================== META DATA ==============================" > "$tmpfile" 
  echo "# $diff_title" >> "$tmpfile"
  echo "# $diff_url" >> "$tmpfile"
  echo "#=====================================================================" >> "$tmpfile"

  # NOTE: Obtain the diff and print it to the patch file
  arc export --revision $1 --git >> "$tmpfile"

  # NOTE: open patch file in neovim 
  $EDITOR "$tmpfile"
}

main "$1"
