#!/usr/bin/env bash

set -e

if [ $(tmux list-sessions | awk -F ':' '{print $1}' | grep -c openvpn) -eq 1 ]; then
  tmux send-keys -t openvpn C-c
else
  tmux new-session -d -s openvpn
fi

tmux send-keys -t openvpn 'cd $HOME' Enter
tmux send-keys -t openvpn 'sudo openvpn --config vpn-corporate.ovpn' Enter
tmux detach -s openvpn
tmux display "VPN Connection started, accept the DUO push!"
