#!/bin/bash

INSTALLDIR=${1:-$HOME/dotfilesTest}
SELECTION=(
  "$PWD/vim/*"
  "$PWD/zsh/*"
  "$PWD/tmux/*"
  "$PWD/git/*"
)

# Determine what dotfiles to install
echo -n "Do you want to use my vim configs? [n/y]"
read -n 1 use_vim_configs

if [ "$use_vim_configs" == "n" ]; then
  unset SELECTION[0]
fi
echo

echo -n "Do you want to use my zsh configs? [n/y]"
read -n 1 use_zsh_configs

if [ "$use_zsh_configs" == "n" ]; then
  unset SELECTION[1]
fi
echo

echo -n "Do you want to use my tmux configs? [n/y]"
read -n 1 use_tmux_configs

if [ "$use_tmux_configs" == "n" ]; then
  unset SELECTION[2]
fi

echo -n "Do you want to use my git configs? [n/y]"
read -n 1 use_git_configs

if [ "$use_git_configs" == "n" ]; then
  unset SELECTION[0]
fi
echo

# Start creating symlinks
shopt -s nullglob
for path in "${SELECTION[@]}"
do
  echo "processing $path"
  echo

  shopt -s nullglob
  for file in $path
  do
    file_name="."${file##*/}
    ln -s $file $INSTALLDIR/$file_name
  done
done

echo
