# Defines environment variables.
export ENABLE_SPRING=0
export DEFAULT_USER=$USER
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export NO_SUGGESTED_REVIEWERS=no

# recommended by brew doctor {{{
  export PATH="/usr/local/bin:$PATH"
  export PATH="/usr/local/sbin:$PATH"
# }}}

export PATH="$HOME/.bin:$PATH" # TODO: evaluate env var
export PATH="/Users/alexander/.scripts:$PATH" # include my own scripts
export PATH="$PATH:/Users/alexander/Development/arcanist/bin"

export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$PATH:/Applications/FontForge.app/Contents/Resources/opt/local/bin" # fontcustom.app path

# TMUX needs screen-256-color
if [ -n "$TMUX" ]; then
  export TERM=tmux-256color;
else
  export TERM=xterm-256color-italic
fi

export XML_CATALOG_FILES="/usr/local/etc/xml/catalog" # TODO: evaluate env var

# Go settings {{{
  export GOPATH=$HOME/golang
  export GOROOT=/usr/local/opt/go/libexec
  export PATH=$PATH:$GOPATH/bin
  export PATH=$PATH:$GOROOT/bin
# }}}

# Java settings {{{
  export JAVA_HOME=`/usr/libexec/java_home`
  export MAVENPATH=$HOME/.maven
  export PATH=$PATH:$MAVENPATH/bin
# }}}

# FZF settings {{{
 export FZF_DEFAULT_OPTS='
   --color fg:000000,bg:#dedcd6,hl:#170080,fg+:#ffffff,bg+:#000000,hl+:#ffffff
   --color info:#000000,prompt:#000000,pointer:#ffffff,marker:#ffffff,spinner:#170080,header:8
 '
# }}}

# LSCOLORS {{{
LS_COLORS='di=01;30' ; export LS_COLORS
# }}}

export VIM_CONFIG_PATH=$HOME/.config/nvim/

# NOTE: fixes issue with too many open files when refreshing paperclip thumbnails:
# https://github.com/thoughtbot/paperclip/issues/1326
export RUN_AT_EXIT_HOOKS=true

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
