
# Start tmux by default and exit terminal if tmux exits. {{{
   if [ -z "$TMUX" ]; then
     # tmux attach-session || exec tmux new-session;
     tmux attach-session || exec tmux new-session && exit;
   fi
# }}}


if [[ $TERM = dumb ]]; then
  unset zle_bracketed_paste
fi

# general functions {{{
  silent_source() {
    path="$1"

    [ -n "$path" ] && return 1

    if [ -f "$path" ]; then
      source "$path"
    fi
  }

  # NOTE: Run command n-times
  # http://serverfault.com/questions/273238/how-to-run-a-command-multiple-times
  times() {
    number=$1
    shift
    for i in `seq $number`; do
      $@
    done
  }

  # NOTE: Run command till the exit code is zero
  try_loop() {
    until [ $? == 0 ]
    do
      echo "LOOPING !!"
      $@
      sleep 0.1
    done
  }

  until_fail() {
    until [ $? != 0 ]
    do
      echo "TRY_FAIL_LOOP"
      $@
      sleep 0.1
    done
  }

  # Keep running cucumber or rspec till
  find_random_fail() {
    command="$1"
    while true; do
      if [[ $command == "cucumber" ]]; then
        echo "running cukes"
        bundle exec cucumber -p parallel
      elif [[ $command == "rspec" ]]; then
        echo "running rspec"
        bin/rescue rspec --order random
      fi
    done
  }

  port() { lsof -n -i:$@ | grep LISTEN; }
  device() { lsof +f -- $@ }

  wifi_signal_strength() {
    while x=1; do /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | grep CtlRSSI; sleep 0.5; done
  }
# }}}

# ZSH highlighting settings {{{
  ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root line)
  ZSH_HIGHLIGHT_PATTERNS+=('Closed' 'fg=cyan,bold,bg=default')
  ZSH_HIGHLIGHT_PATTERNS+=('Needs Review' 'fg=magenta,bold,bg=default')
  ZSH_HIGHLIGHT_PATTERNS+=('Needs Revision' 'fg=red,bold,bg=default')
  ZSH_HIGHLIGHT_PATTERNS+=('Accepted' 'fg=green,bold,bg=default')
  ZSH_HIGHLIGHT_PATTERNS+=('No Revision' 'fg=blue,bold,bg=default')
  ZSH_HIGHLIGHT_PATTERNS+=('Abandoned' 'fg=default,bold,bg=default')
  ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=white,bold,bg=red')
  ZSH_HIGHLIGHT_PATTERNS+=('sudo' 'fg=white,bold,bg=red')

  # FIXME: this should not be necessary if we dedicate the bright
  # color variations for grays
  # NOTE: Customize some zsh syntax highlight settings
  typeset -A ZSH_HIGHLIGHT_STYLES
  ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='none'
  ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='none'
  ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='none'
  ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='none'
  ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='none'
  ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='none'
  ZSH_HIGHLIGHT_STYLES[rc-quote]='none'
  ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='none'
  ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='none'
  ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='none'
# }}}

# Vi mode {{{
  bindkey -v
  export KEYTIMEOUT=1

  autoload -U edit-command-line
  zle -N edit-command-line
  bindkey -M vicmd v edit-command-line
# }}}

# completions {{{
  zmodload zsh/complist
  autoload -U compinit && compinit
  zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
  # use the tag name as group name
  zstyle ':completion:*' group-name ''
  # format all messages not formatted in bold prefixed with ----
  zstyle ':completion:*' format '%B---- %d%b'
  # format descriptions (notice the vt100 escapes)
  zstyle ':completion:*:descriptions'    format $'%{\e[0;31m%}completing %B%d%b%{\e[0m%}'
  # bold and underline normal messages
  zstyle ':completion:*:messages' format '%B%U---- %d%u%b'
  # format in bold red error messages
  zstyle ':completion:*:warnings' format "%B$fg[red]%}---- no match for: $fg[white]%d%b"
  # activate menu selection
  zstyle ':completion:*' menu select
  # activate approximate completion, but only after regular completion (_complete)
  zstyle ':completion:::::' completer _complete _approximate
  # limit to 2 errors
  zstyle ':completion:*:approximate:*' max-errors 2
# }}}

# Zplug plugin definitions {{{
  unset ZPLUG_CACHE_FILE # Fix for ZPLUG_CACHE_FILE deprecation
  source ~/.zplug/init.zsh
  zplug "alexanderjeurissen/ombre.zsh", use:prompt_ombre_setup
  zplug "zsh-users/zsh-syntax-highlighting"
  zplug "zsh-users/zsh-completions"
  zplug "zsh-users/zsh-autosuggestions"
# }}}

# aliasses {{{
  alias textedit="/Applications/TextEdit.app/Contents/MacOS/TextEdit"
  alias l="LC_COLLATE=C \gls -lAh --color=auto --time-style="+%Y-%m-%d +%H:%M:%S" --group-directories-first"
  alias ls="\gls --color=auto --group-directories-first"
  alias rls="cd && cd - && ls -G"
  alias fixtestdb="bin/rake db:test:prepare"
  alias upd="git pull origin develop:develop --rebase --ff-only"
  alias upm="git pull origin master:master --rebase --ff-only"
  alias rake="noglob bin/rake"
  alias console="bin/rails console"
  alias migrate="bin/rake db:migrate && bin/rake db:test:prepare"
  alias migrate_redo="noglob bin/rake db:migrate:redo"
  alias migrate_undo="noglob bin/rake db:migrate:down"
  alias chrome="CAPYBARA_DRIVER=\"selenium\""
  alias rerun="bundle exec cucumber -p rerun"
  alias routes="rails_routes | fzf | pbcopy"
  alias pryr="pry -r ./config/environment -r rails/console/app -r rails/console/helpers"
  alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
  alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
  alias showDriveUsage='sudo lsof'
  alias tn='tmux new -s "${$(basename `PWD`)//./}" || tmux at -t "${$(basename `PWD`)//./}"'
  alias kn='kak -d -s "${$(basename `PWD`)//./}"'
  alias attach="tmux attach -t"
  alias findP="ps -ef | grep -v grep | grep "
  alias applypatch="git am --signoff <"
  alias create_commit_range_patch="git format-patch"
  alias prof="source ~/.zshrc && source ~/.zshenv && source ~/.zprofile"
  alias structuresql="g difftool develop -- db/structure.sql"
  alias check_failing_jenkins_specs="bin/rspec $(pbpaste)"
  alias remove_zsh_cache="rm ~/.zcompdump && rm -rf ~/.zsh_cache/ && rm -rf ~/.zplug/zcompdump && rm -rf ~/.zplug/zcompdump.zwc"
  alias verify_approvals="approvals verify -d nvim -d  -a"
  # FIXME: https://github.com/alexanderjeurissen/dotfiles/issues/14 {{{
  alias fixlint="git add -A && git commit -m 'Addressed lint warnings.'"
  alias fixspecs="git add -A && git commit -m 'fixed failing specs.'"
  # }}}
  alias eslintspecific="yarn run eslint:specific -- --fix"
  # FIXME: https://github.com/alexanderjeurissen/dotfiles/issues/15 {{{
  alias yarn_global_add='yarn global add --global-folder=`yarn global bin` '
  alias yarn_global_remove='yarn global remove --global-folder=`yarn global bin` '
  # }}}
  alias urldecode='python -c "import sys, urllib as ul; \
    print ul.unquote_plus(sys.argv[1])"'

  alias urlencode='python -c "import sys, urllib as ul; \
    print ul.quote_plus(sys.argv[1])"'
  alias disable_mouse_acceleration='defaults write .GlobalPreferences com.apple.mouse.scaling -1'
  alias mutt='TERM=screen-256color neomutt'
  alias neomutt='TERM=screen-256color \neomutt'
  alias no_unexpected='git checkout db/structure.sql app/models/bounty.rb'
  # NOTE: needed seeing as remote servers likely won't have my custom tic
  alias ssh='TERM=xterm-256color ssh'
# }}}

# Alias for pentesting/hacking {{{
  alias burp='java -jar -Xmx3072m ~/Git/hackerij/burp.jar'
  alias proxy-on="sudo networksetup -setsecurewebproxy 'Wi-Fi' 127.0.0.1 12345 && sudo networksetup -setwebproxy 'Wi-Fi' 127.0.0.1 12345"
  alias proxy-off="sudo networksetup -setsecurewebproxystate 'Wi-Fi' off && sudo networksetup -setwebproxystate 'Wi-Fi' off"
  alias subbrute="$HOME/git/hackerij/subbrute/subbrute.py"
  alias burp="open $HOME/git/hackerij/burp.jar"
# }}}

# Aliases for common typo's {{{
  alias cd..='cd ..'
  alias cd..l='cd .. && l'
  alias cd..ls='cd .. && ls'
  alias clera="clear"
# }}}

# Nvim & vim aliases {{{
  alias v='nvim'
# }}}

# Aliases for Arcanist {{{
  alias diff="arc diff --nounit --excuse \"jenkins\""
  alias diffb="arc diff --browse"
  alias diffu="arc diff --nounit --excuse \"jenkins\" --verbatim"

  # FIXME: {{{
    nexttask() {
      next_task=`arc task | egrep -o 'T\d+' | head -1`
      echo $next_task | pbcopy
      arc browse $next_task
    }
  # }}}

  browse() {
    case $1 in
      diffs)
        objects=`arc list`
        [ -z $objects ] && return 1
        chosen_object=`echo $objects | fzf | egrep -o 'D\d+'`
        ;;

      tasks)
        objects=`arc tasks`
        [ -z $objects ] && return 1
        chosen_object=`echo $objects | fzf | egrep -o 'T\d+'`
        ;;
      *)
        echo "Usage: $0 {diffs|tasks}"
        return 1
    esac

    if [ -z $chosen_object ]; then
      echo "operation cancelled"
      return 1
    fi

    arc browse "${chosen_object}"
  }

  # NOTE: Cherrypick diff by applying it without commit and no branch
  # Then commit it with message: "Patch <diff-id> (TODO: remove this commit before landing)
  cherrypick() {
    arc patch --nocommit --nobranch "${1}"
    git commit -a -m "Patch ${1} (TODO: remove this commit before landing)"
  }
# }}}

# Aliases for directories {{{
  alias h1="cd ~/git/hackerone/"
  alias payments="cd ~/git/hackerone-payments/"
  alias dotfiles="cd ~/git/dotfiles/"
# }}}

# Aliases for foreman and psql {{{
  alias psql_rails='psql -U alexanderjeurissen -p 3100 -h localhost -d postgres'
  alias startServices="foreman start -c all=0,redis=1,postgresql=1,mailcatcher=1,payments_dev=1,payments_test=1,sidekiq=1"
  alias startBackend="rails s"
  alias startFrontend="foreman start -c all=0,sass=1,webpack=1,uidocs=1,karma=1"
  alias startGuard="bundle exec guard -d --no-interactions"
  alias startAll="startServices && startBackend && startFrontend"
  alias neo4j="db/neo4j/development/bin/neo4j"
# }}}

# Alias for clearing the screen
alias clear!="clear && printf '\e[3J'"

# set nvim as defaut editor
export EDITOR="nvim"

# FZF {{{
# --files: List files that would be searched but do not search
# --ignore: Do respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
  # export FZF_DEFAULT_COMMAND='ag -l -g ""'
  export FZF_DEFAULT_COMMAND='rg --files --smart-case --hidden --follow --no-messages --ignore-file ~/.gitignore'

  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# }}}

export TMPDIR="/private/tmp" # fix vim-dispatch/issues/64

# Zplug {{{
# Can manage local plugins
# zplug "~/.zsh", from:local

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
  printf "Install? [y/N]: "

  if read -q; then
    echo; zplug install
  fi
fi

# Then, source plugins and add commands to $PATH
# Only source zplugins when a new terminal is opened not when source ~/.zshrc
# This is due to conflict between some plugins that causes a crash
# https://github.com/zsh-users/zsh-autosuggestions/issues/205
if [[ $ZSH_EVAL_CONTEXT == 'file' ]]; then
  zplug load
fi
# }}}

# git aliases {{{
  source ~/.gitaliases
  alias changedfiles= "git diff --name-only | uniq | xargs nvim"
# }}}

# History options {{{
  if [ -z "$HISTFILE" ]; then
    HISTFILE=$HOME/.zsh_history
  fi

  HISTSIZE=10000
  SAVEHIST=10000

  setopt append_history
  setopt extended_history
  setopt hist_expire_dups_first
  setopt hist_ignore_dups # ignore duplication command history list
  setopt hist_ignore_space
  setopt hist_verify
  setopt inc_append_history
  setopt share_history # share command history data
#}}}

# Nginx {{{
  nginx_setup() {
    local dest=$(brew --prefix)/etc/nginx/sites/$(basename `pwd`).conf

    $(cp ~/.dotfiles/nginx/template.conf $dest)
    $(sed -ie "s/APP_NAME/$(basename `PWD`)/g" $dest)
    $(sed -ie "s@APP_PATH@$PWD@g" $dest)
    $(sudo nginx -s reload)
  }

  # Create nginx conf for current git repo
  alias devlink='nginx_setup'
  alias sites='ranger $(brew --prefix)/etc/nginx/sites/'
# }}}

# Auto suggestions {{{
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=242'
bindkey '^e' autosuggest-accept
# }}}

# Fzf functions {{{
  # fbr - checkout git branch (including remote branches)
  __fzf_branch() {
    local cmd='git branch'

    if which arc > /dev/null; then
      cmd="arcbranchansi"
    fi

    setopt localoptions pipefail 2> /dev/null
    eval "$cmd" | FZF_DEFAULT_OPTS="--ansi --height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_CTRL_T_OPTS" $(__fzfcmd) -m "$@" | while read item; do
      echo -n "${(q)item} " | cut -d'\' -f1
    done
    local ret=$?
    # echo
    return $ret
  }

  branch-widget() {
    LBUFFER="${LBUFFER}$(__fzf_branch)"
    local ret=$?
    zle redisplay
    typeset -f zle-line-init >/dev/null && zle zle-line-init
    return $ret
  }
  zle     -N   branch-widget
  bindkey '^B' branch-widget

  __fzf_tasks() {
    if ! which arc > /dev/null; then
      return 1
    fi

    local cmd="arctasksansi"

    setopt localoptions pipefail 2> /dev/null
    eval "$cmd" | FZF_DEFAULT_OPTS="--ansi --height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_CTRL_T_OPTS" $(__fzfcmd) -m "$@" | while read item; do
      echo -n "${(q)item} " | cut -d'\' -f1
    done
    local ret=$?
    # echo
    return $ret
  }

  tasks-widget() {
    LBUFFER="${LBUFFER}$(__fzf_tasks)"
    local ret=$?
    zle redisplay
    typeset -f zle-line-init >/dev/null && zle zle-line-init
    return $ret
  }

  bindkey '^F' fzf-file-widget # use ^F for file completion insetad of ^T which I use for tasks
  zle     -N   tasks-widget
  bindkey '^T' tasks-widget

  # fstash - easier way to deal with stashes
  # type fstash to get a list of your stashes
  # enter shows you the contents of the stash
  # ctrl-d shows a diff of the stash against your current HEAD
  # ctrl-b checks the stash out as a branch, for easier merging
  zmodload zsh/mapfile # Needsed for mappin the files in fstash
  stashlist() {
    local out q k sha
    while out=$(
      git stash list --pretty="%C(yellow)%h %>(14)%Cgreen%cr %C(blue)%gs" |
      fzf --ansi --no-sort --query="$q" --print-query \
          --expect=ctrl-d,ctrl-b);
    do
      $mapfile -t out <<< "$out"
      q="${out[0]}"
      k="${out[1]}"
      sha="${out[-1]}"
      sha="${sha%% *}"
      [[ -z "$sha" ]] && continue
      if [[ "$k" == 'ctrl-d' ]]; then
        git diff $sha
      elif [[ "$k" == 'ctrl-b' ]]; then
        git stash branch "stash-$sha" $sha
        break;
      else
        git stash show -p $sha
      fi
    done
  }
# }}}
$(silent_source "$HOME/Development/arcanist/resources/shell/bash-completion")

# NOTE: this hopefully fools workstation init
# script that this line is already in my zshrc
# I prefer defining these path variables in my zshenv
# export PATH="/Users/alexanderjeurissen/Development/arcanist/bin:$PATH"

# vim: foldmethod=marker:sw=2
