#!/usr/bin/env bash 

if echo `ifconfig` | egrep 'inet 10' > /dev/null; then
  echo "#[bg=green, fg=black, bold]  VPN #[bg=default, fg=default, nobold]"
else 
  echo "#[bg=red, fg=black, bold]  NO VPN #[bg=default, fg=default, nobold]"
fi
