[information]
 name = "macos_aqua"
 background = "light"
 author = 'Alexander Jeurissen <alexander@jeurissen.email>'

[palette]
 fg = '#212121'
 bg = '#EAE9E8'

 white = '#FFFFF'
 gray = '#5A6770'
 blue = '#007BFF'
 green = '#13C759'
 cyan = '#50ABF3'
 red = '#FF3C31'

 orange = '#FF9501'
 yellow = '#FFCC02'

 purple = '#5857D6'
 magenta = '#BF78DB'

 black = '#212121'
