[[plugins]]
repo = 'Shougo/dein.vim'
# NOTE: Let dein manage dein

# PLUGINS: ColorSchemes {{{
  # [[plugins]]
  # repo = 'morhetz/gruvbox'
  # hook_post_source = '''
  #   syntax enable
  #   let g:gruvbox_italic=1
  #   let g:gruvbox_italicize_strings=1
  #   let g:gruvbox_contrast_dark='soft'
  #   let g:gruvbox_contrast_light='soft'
  # '''

  [[plugins]]
  repo = 'lifepillar/vim-solarized8'
  hook_post_source = '''
    syntax enable
    let g:solarized_extra_hi_groups=1
    let g:solarized_italics = 1

    color solarized8_high
  '''

  [[plugins]]
  repo='tsiemens/vim-aftercolors'
# }}}

# PLUGINS: Core {{{
  [[plugins]]
  repo = 'Konfekt/FastFold'

  [[plugins]]
  repo = 'vim-scripts/searchfold.vim'

  [[plugins]]
  repo = 'tpope/vim-dispatch'
  # NOTE: run tasks in a tmux split to not block vim

  [[plugins]]
  repo = 'nvim-treesitter/nvim-treesitter'
  merged = 0
  # NOTE: Treesitter configurations and abstraction layer for Neovim (highlights).

  [[plugins]]
  repo = 'vim-test/vim-test'
  on_cmd = ['TestNearest', 'TestFile', 'TestSuite', 'TestLast', 'TestVisit']
  hook_post_source = '''
    let test#strategy = "dispatch"
  '''

  [[plugins]]
  repo = 'tpope/vim-scriptease'
  # NOTE: A Vim plugin for making Vim plugins.

  [[plugins]]
  repo = 'neoclide/coc.nvim'
  rev = 'release'
  merged = 0
  # NOTE: Common configurations for Neovim Language Servers

  # [[plugins]]
  # repo = 'haorenW1025/completion-nvim'
  # NOTE: LSP autocomplete

  [[plugins]]
  repo = 'christoomey/vim-tmux-navigator'
# }}}

# PLUGINS: Editing {{{
  [[plugins]]
  repo = 'tpope/vim-abolish'
  on_cmd = ['Abolish', 'Subvert']
  # NOTE: better search and replace

  [[plugins]]
  repo = 'tpope/vim-endwise'
  # NOTE: insert end after certain keywords in ruby

  [[plugins]]
  repo = 'tpope/vim-commentary'
  # NOTE: Easy commenting using vim motions

  [[plugins]]
  repo = 'bogado/file-line'
  # NOTE: allow opening files with line number e.g. file.txt:30

  [[plugins]]
  repo = 'tommcdo/vim-exchange'
  # NOTE: ...

  [[plugins]]
  repo = 'tpope/vim-repeat'
  # NOTE: ...

  [[plugins]]
  repo = 'tpope/vim-surround'
  depends = 'vim-repeat'
  # NOTE: ...

  [[plugins]]
  repo = 'tpope/vim-sleuth'
  # NOTE: smart indent width based on buffer and neigbouring files

  [[plugins]]
  repo = 'machakann/vim-highlightedyank'
  # NOTE: yank visual selections

  [[plugins]]
  repo = 'stefandtw/quickfix-reflector.vim'
  # NOTE: Enables editing quickfix buffer
# }}}

# PLUGINS: Frontend/Javascript {{{
  [[plugins]]
  repo = 'ap/vim-css-color'
  on_ft = ['css', 'scss', 'conf', 'javascript']
  # NOTE: yank visual selections

  # [[plugins]]
  # repo = 'billyvg/tigris.nvim'
  # on_ft = ['javascript', 'html.javascript']
  # NOTE: semantic highlighting for javascript

# }}}

# PLUGINS: Ruby {{{
  [[plugins]]
  repo = 'tpope/vim-bundler'
  # NOTE: run bundler commands in Vim

  [[plugins]]
  repo = 'tpope/vim-cucumber'
  on_ft = 'cucumber'
  # NOTE: fancy cucumber highlighting

  # [[plugins]]
  # repo = 'tpope/vim-rails'
  # on_ft = ['ruby', 'cucumber']
  # NOTE: rails specific config and highlight
# }}}

# PLUGINS: Navigation {{{
  [[plugins]]
  repo = 'octref/RootIgnore'
  # NOTE: ...

  [[plugins]]
  repo = 'junegunn/fzf'
  build = './install --all'
  merged = 0
  # NOTE: Fuzzy finder / selector

  [[plugins]]
  repo = 'moll/vim-bbye'
  # NOTE: add nice buffer deleting

  [[plugins]]
  repo = 'arithran/vim-delete-hidden-buffers'
  # NOTE: rails specific config and highlight

  [[plugins]]
  repo = 'tpope/vim-vinegar'
  # NOTE: File browser

  [[plugins]]
  repo = 'tpope/vim-eunuch'
  # NOTE: ...

  [[plugins]]
  repo = 'gcmt/taboo.vim'
  # NOTE: Tab rename utilities

  [[plugins]]
  repo = 'airblade/vim-rooter'
  # NOTE: change vim root to vcs root when editing a file

  [[plugins]]
  repo = 'tpope/vim-unimpaired'
  # NOTE: pairs of handy bracket mappings like [f and ]f for file switching

  [[plugins]]
  repo = 'thinca/vim-visualstar'
  on_map = '*'
  # NOTE: allows to use the * motion in visual mode
# }}}

# PLUGINS: Version Control {{{
  [[plugins]]
  repo = 'sgeb/vim-diff-fold'
  # NOTE: allows to fold vim diffs

  [[plugins]]
  repo = 'tpope/vim-fugitive'
  # NOTE: adds git commands for checking git status, commit etc.

  [[plugins]]
  repo = 'tpope/vim-git'
  # NOTE: Vim runtime files and syntax highlighting
# }}}

# PLUGINS: Window Management {{{
  [[plugins]]
  repo = 'szw/vim-maximizer'
  # NOTE: allows to zoom into splits
# }}}

# vim: foldmethod=marker:sw=2:foldlevel=10
