# ROCKS: List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks] # {{{
# }}}

# PLUGINS: List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins] # {{{
"rocks.nvim" = "2.44.0"
"rocks-config.nvim" = "3.1.0"
"rocks-git.nvim" = "2.5.3"
"rocks-lazy.nvim" = "scm"
"rocks-treesitter.nvim" = "1.3.0"

"plenary.nvim" = "scm"
"telescope-zf-native.nvim" = "1.0.0"
"telescope.nvim" = "scm"
neorg-telescope = "1.2.2"

nvim-lspconfig = "2.1.0"

"oil.nvim" = "2.15.0"
"unimpaired.nvim" = "0.4.0"
"guess-indent.nvim" = "scm"
nvim-web-devicons = "0.100"
"nvim-colorizer.lua" = "scm"
nvim-surround = "3.1.1"
promise-async = "scm"
nvim-ufo = "1.5.0"

"diffview.nvim" = "scm"
neogit = "2.0.0"
neotest = "5.8.0"
neotest-jest = "scm"
neotest-rspec = "scm"
cmp-nvim-lsp = "scm"
cmp-cmdline = "scm"
nvim-cmp = "scm"
cmp-path = "scm"
cmp-buffer = "scm"
neorg = "9.3.0"
tree-sitter-toml = "scm"
tree-sitter-lua = "scm"
tree-sitter-ruby = "scm"
tree-sitter-yaml = "scm"
tree-sitter-markdown = "scm"
tree-sitter-json = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-tsx = "scm"
nvim-treesitter-legacy-api = "0.9.2"
tree-sitter-typescript = "scm"
tree-sitter-javascript = "scm"
tree-sitter-ecma = "scm"
tree-sitter-jsx = "scm"
tree-sitter-vim = "scm"
tree-sitter-graphql = "scm"
tree-sitter-scss = "scm"
tree-sitter-embedded_template = "scm"
tree-sitter-norg = "0.2.6"
tree-sitter-sql = "scm"
"headlines.nvim" = "scm"
tree-sitter-python = "scm"
tree-sitter-css = "scm"
tree-sitter-bash = "scm"
tree-sitter-gitcommit = "scm"
tree-sitter-xml = "scm"
tree-sitter-regex = "scm"
tree-sitter-markdown_inline = "scm"
tree-sitter-swift = "0.0.53"
tree-sitter-git_config = "0.0.30"
tree-sitter-diff = "0.0.32"
tree-sitter-ini = "0.0.32"

[plugins."CopilotChat.nvim" ]
git = "CopilotC-Nvim/CopilotChat.nvim"
rev = "v3.11.1"


[plugins."tailwind-tools.nvim" ]
git = "luckasRanarison/tailwind-tools.nvim"
rev = "v0.3.2"

[plugins."lspkind.nvim" ]
git = "onsails/lspkind.nvim"
rev = "cff4ae321a91ee3473a92ea1a8c637e3a9510aec"

[plugins."blame.nvim" ]
git = "FabijanZulj/blame.nvim"
rev = "dedbcdce857f708c63f261287ac7491a893912d0"

[plugins."fileline.nvim" ]
git = "lewis6991/fileline.nvim"
rev = "c116aa8dd7aa7e1db6938f872285e598dc9ee00b"

[plugins."modus-themes.nvim" ]
git = "miikanissi/modus-themes.nvim"
rev = "v1.4.0"

[plugins."vim-bbye" ]
git = "moll/vim-bbye"
rev = "v1.0.1"

[plugins."vim-visualstar" ]
git = "thinca/vim-visualstar"
rev = "v0.5.0"

[plugins."kommentary" ]
git = "b3nj5m1n/kommentary"
rev = "v1.0"

[plugins."vim-exchange" ]
git = "tommcdo/vim-exchange"
rev = "d6c1e9790bcb8df27c483a37167459bbebe0112e"

[plugins."todo-comments.nvim" ]
git = "folke/todo-comments.nvim"
rev = "v1.4.0"

[plugins."claude-code.nvim" ]
git = "greggh/claude-code.nvim"
rev = "v0.4.3"

# BUNDLES: bundles allow for a single plugins/x.lua file per bundle instead of per plugin
# {{{

[bundles.neorg]
items = [
  "neorg",
  # "neorg-contexts"
]

[bundles.git]
items = [
  "neogit",
  "diffview.nvim",
]

[bundles.telescope]
items = [
  "neorg-telescope",
  "telescope-zf-native.nvim",
  "telescope.nvim"
]

[bundles.testing]
items = [
  "neotest",
  "neotest-jest",
  "neotest-rspec"
]

[bundles.autocomplete]
items = [
  "nvim-cmp",
  "cmp-path",
  "cmp-buffer",
  "cmp-cmdline",
  "cmp-nvim-lsp",
  "lspkind.nvim"
]
# }}}

[config] # {{{
plugins_dir = "plugins/"
auto_setup = true
# }}}

[treesitter] # {{{
auto_highlight = "all"
auto_install = "false" # prompt | true | false

[treesitter.parser_map]
typescriptreact = "tsx"
# }}}

# vim: foldmethod=marker:sw=2:foldlevel=10
