# ROCKS: List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks] # {{{
# }}}

# PLUGINS: List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins] # {{{
"rocks.nvim" = "2.38.2"
"rocks-config.nvim" = "2.2.0"
"rocks-git.nvim" = "2.0.1"
"rocks-lazy.nvim" = "scm"
"rocks-treesitter.nvim" = "1.0.3"

"plenary.nvim" = "scm"
"telescope-zf-native.nvim" = "1.0.0"
"telescope.nvim" = "scm"
neorg-telescope = "1.2.2"

nvim-lspconfig = "0.1.8"

"oil.nvim" = "2.12.1"
"unimpaired.nvim" = "0.2.0"
"guess-indent.nvim" = "scm"
nvim-web-devicons = "0.100"
"nvim-colorizer.lua" = "scm"
nvim-surround = "2.1.5"
promise-async = "scm"
nvim-ufo = "1.4.0"

"diffview.nvim" = "scm"
neogit = "1.0.0"
neotest = "5.4.1"
neotest-jest = "scm"
neotest-rspec = "scm"
cmp-nvim-lsp = "scm"
cmp-cmdline = "scm"
nvim-cmp = "scm"
cmp-path = "scm"
cmp-buffer = "scm"
neorg = "9.1.1"
copilot-cmp = "scm"
"copilot.lua" = "scm"
tree-sitter-toml = "0.0.2"
tree-sitter-lua = "0.0.2"
tree-sitter-ruby = "0.0.3"
tree-sitter-yaml = "0.0.2"
tree-sitter-markdown = "0.0.2"
tree-sitter-json = "0.0.3"
tree-sitter-vimdoc = "0.0.2"
tree-sitter-tsx = "0.0.3"
nvim-treesitter-legacy-api = "0.9.2"
tree-sitter-typescript = "0.0.3"
tree-sitter-javascript = "0.0.3"
tree-sitter-ecma = "0.0.2"
tree-sitter-jsx = "0.0.2"
tree-sitter-vim = "0.0.3"
tree-sitter-graphql = "0.0.2"
tree-sitter-scss = "0.0.2"
tree-sitter-embedded_template = "0.0.3"
tree-sitter-norg = "0.2.4"
tree-sitter-sql = "0.0.3"
orgmode = "0.3.5"
tree-sitter-orgmode = "1.3.2"
"headlines.nvim" = "scm"
tree-sitter-python = "0.0.3"
"noice.nvim" = "4.5.0"

[plugins."org-bullets.nvim" ]
git = "akinsho/org-bullets.nvim"
rev = "ab8e1d860d61239c4fe187ead15f73bb2561acd1"

[plugins."tailwind-tools.nvim" ]
git = "luckasRanarison/tailwind-tools.nvim"
rev = "v0.3.0"

[plugins."lspkind.nvim" ]
git = "onsails/lspkind.nvim"
rev = "cff4ae321a91ee3473a92ea1a8c637e3a9510aec"

[plugins."blame.nvim" ]
git = "FabijanZulj/blame.nvim"
rev = "dedbcdce857f708c63f261287ac7491a893912d0"

[plugins."fileline.nvim" ]
git = "lewis6991/fileline.nvim"
rev = "c116aa8dd7aa7e1db6938f872285e598dc9ee00b"

[plugins."modus-themes.nvim" ]
git = "miikanissi/modus-themes.nvim"
rev = "v1.3.2"

[plugins."vim-bbye" ]
git = "moll/vim-bbye"
rev = "v1.0.1"

[plugins."vim-visualstar" ]
git = "thinca/vim-visualstar"
rev = "v0.5.0"

[plugins."kommentary" ]
git = "b3nj5m1n/kommentary"
rev = "v1.0^{}"

[plugins."vim-exchange" ]
git = "tommcdo/vim-exchange"
rev = "d6c1e9790bcb8df27c483a37167459bbebe0112e"

[plugins."todo-comments.nvim" ]
git = "folke/todo-comments.nvim"
rev = "v1.3.0"

# BUNDLES: bundles allow for a single plugins/x.lua file per bundle instead of per plugin
# {{{
[bundles.orgmode]
items=[
  "orgmode",
  "org-bullets.nvim",
  "tree-sitter-orgmode"
]

[bundles.neorg]
items = [
  "neorg",
  # "neorg-contexts"
]

[bundles.git]
items = [
  "neogit",
  "diffview.nvim",
]

[bundles.telescope]
items = [
  "neorg-telescope",
  "telescope-zf-native.nvim",
  "telescope.nvim"
]

[bundles.testing]
items = [
  "neotest",
  "neotest-jest",
  "neotest-rspec"
]
[bundles.autocomplete]
items = [
  "nvim-cmp",
  "cmp-path",
  "cmp-buffer",
  "cmp-cmdline",
  "cmp-nvim-lsp",
  "copilot-cmp",
  "copilot.lua",
  "lspkind.nvim"
]
# }}}

[config] # {{{
plugins_dir = "plugins/"
auto_setup = true
# }}}

[treesitter] # {{{
auto_highlight = "all"
auto_install = "false" # prompt | true | false

[treesitter.parser_map]
typescriptreact = "tsx"
# }}}

# vim: foldmethod=marker:sw=2:foldlevel=10
