#!/usr/bin/env bash

# NOTE: Copied from Tpope's blogpost which can be found at
# https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
mv "$dir/$$.tags" "$dir/tags"
