#!/usr/bin/env bash

# NOTE: Copied from Tpope's blogpost which can be found at
# https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

case "$1" in
  rebase) exec .git/hooks/post-merge ;;
esac

