#!/usr/bin/env bash

# This script uses the hl script to highlight certain
# keywords in the arc branch output
# The color output of arc branch is lost when it's piped
# this makes sure that ansi colors are returned 
# which won't get lost when piped to fzf --ansi
arc branch --view-all | 
hl 'Closed' 2 |
hl 'Needs Review' 5 |
hl 'Needs Revision' 1 |
hl 'Accepted' 2 |
hl 'No Revision' 4 |
hl 'Changes Planned' 3
