#!/usr/bin/env bash

# This script uses the hl script to highlight certain
# keywords in the arc tasks output
# The color output of arc branch is lost when it's piped
# this makes sure that ansi colors are returned
# which won't get lost when piped to fzf --ansi
arc tasks |
hl 'T\d+' 3 |
hl 'Closed' 1 |
hl 'Open' 2 |
hl 'Needs Triage' 5 |
hl 'Normal' 1
