#!/usr/bin/env bash

main() {
  local cueFile=$1
  local flacFile=$2

  if [ -z $cueFile ]; then cueFile=$(ls _scans/*.cue | head -1); fi
  if [ -z $flacFile ]; then flacFile=$(ls *.flac | head -1); fi
  if [ -z $flacFile ]; then flacFile=$(ls *.wav | head -1); fi
  
  local flacFilesBeforeSplitting=$(ls *.flac | wc -l)

  # NOTE: split the flac file.
  shnsplit -f "$cueFile" -t %n-%t -o flac "$flacFile" &
  wait

  # NOTE: print stats to see if everything went according to plan
  local cueLines=$(cueprint -d '%N\n' "$cueFile")
  local flacFilesAfterSplitting=$(ls *.flac | wc -l)
  local createdFlacFiles=$((flacFilesAfterSplitting-flacFilesBeforeSplitting))

  echo "============================[Stats]================================="
  echo "'$flacFile' was split using '$cueFile'"
  echo "--------------------------------------------------------------------"
  echo "Flac files before splitting: $flacFilesBeforeSplitting"
  echo "Flac files after splitting: $flacFilesAfterSplitting" 
  echo "--------------------------------------------------------------------"
  echo "tracks listed in cue file: $cueLines"
  echo "actual created Flac files: $createdFlacFiles"
  echo "===================================================================="

  if [ "$createdFlacFiles" == "$cueLines" ]; then
    rmtrash "$flacFile"
  fi
}

main "$1" "$2"
