#!/bin/bash

# Resolve symlinks to their target files
NVIM_CONFIG=$(readlink -f ~/.config/nvim/init.lua)
WEZTERM_CONFIG=$(readlink -f ~/.config/wezterm/wezterm.lua)

# Temporary files
TEMP_NVIM=$(mktemp)
TEMP_WEZTERM=$(mktemp)

# Change background to dark in Neovim config
sed 's/o.background = light/o.background = dark/' "$NVIM_CONFIG" > "$TEMP_NVIM" && mv "$TEMP_NVIM" "$NVIM_CONFIG"

# Change colorscheme to modus_vivendi in Neovim config
sed 's/vim.cmd.colorscheme "modus_operandi"/vim.cmd.colorscheme "modus_vivendi"/' "$NVIM_CONFIG" > "$TEMP_NVIM" && mv "$TEMP_NVIM" "$NVIM_CONFIG"

# Change color scheme to Modus Vivendi in WezTerm config
sed 's/config.color_scheme = "Modus Operandi"/config.color_scheme = "Modus Vivendi"/' "$WEZTERM_CONFIG" > "$TEMP_WEZTERM" && mv "$TEMP_WEZTERM" "$WEZTERM_CONFIG"

# Clean up temporary files
rm -f "$TEMP_NVIM" "$TEMP_WEZTERM"
