#!/usr/bin/env bash

main() {
  rmtrash .DS_STORE
  rmtrash .Trashes
  rmtrash *.m3u

  mkdir _scans

  mv *.cue _scans/
  mv *.CUE _scans/

  mv *.log _scans/
  mv *.LOG _scans/

  mv *.jpg _scans/
  mv *.JPG _scans/

  mv *.jpeg _scans/
  mv *.JPEG _scans/

  mv *.png _scans/
  mv *.PNG _scans/

  mv *.pdf _scans/
  mv *.PDF _scans/

  mv Artwork/*.* _scans/
  mv Covers/*.* _scans/
  mv scan/*.* _scans/
  mv Scans/*.* _scans/

  rmtrash Covers
  rmtrash Artwork
  rmtrash scan
  rmtrash Scans

  echo ""
  echo ""

  LC_COLLATE=C \gls -lAh --color=auto --time-style="+%Y-%m-%d +%H:%M:%S" --group-directories-first _scans/
}

main
