#!/bin/bash
file_path="$(echo $1 | cut -d':' -f1)"
spec="$1"

if ! [ -f $file_path ]; then
  echo "File does not exist"
  exit 1
fi

# cucumber_command='bin/cucumber'
# rspec_command='bin/rspec --color --fail-fast'

# ! [ -f 'bin/cucumber' ] && 
cucumber_command='bundle exec cucumber' 
# ! [ -f 'bin/rspec' ] && 
rspec_command='bundle exec rspec --color --fail-fast' 

if [[ $file_path == *.feature ]]; then
  $cucumber_command $spec
elif [[ $file_path == *_spec.rb ]]; then
  $rspec_command $spec
else
  echo "Invalid spec file given."
  exit 1
fi
