#!/usr/bin/env bash

file_path="$(cut -d ':' -f1 <<< "$1")"
spec="$1"

if [[ ! -f "$file_path" ]]; then
  echo "File does not exist"
  exit 1
fi

cucumber_command='bundle exec cucumber' 
rspec_command='bundle exec rspec --color' 

if [[ $file_path == *.feature ]]; then
  # FIVEMAT_PROFILE=1 $cucumber_command $spec --format Fivemat
  $cucumber_command $spec
elif [[ $file_path == *_spec.rb ]]; then
  # FIVEMAT_PROFILE=1 $rspec_command $spec --format Fivemat
  $rspec_command $spec 
else
  echo "Invalid spec file given."
  exit 1
fi
