#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
fpath+=("/usr/local/share/zsh/site-functions")
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# source "$HOME/base16-solarized.light.sh"

# symlink hub to git
# eval "$(hub alias -s)"

# Customize to your needs...
alias rake="noglob rake"
alias pryr="pry -r ./config/environment -r rails/console/app -r rails/console/helpers"
alias bower="noglob bower"
alias rubocop="/Users/alexander/.rbenv/versions/2.1.0/bin/rubocop"
alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias gd='git diff'
alias sq='sequelize'
alias gcc='gcc-5'
alias c++='c++-5'
alias tn='tmux new -s "$(basename `pwd`)" || tmux at -t "$(basename `pwd`)"'
alias findP='ps -ef | grep -v grep | grep '

# this alias creates shortcuts for gui emacs
alias es='/Applications/Emacs.app/Contents/MacOS/Emacs --daemon'
alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs -c -n'
export EDITOR='/Applications/Emacs.app/Contents/MacOS/Emacs'

# Aliases for common typo's
alias cd..='cd ..'
alias cd..l='cd .. && l'
alias cd..ls='cd .. && ls'

alias attach='tmux attach -t'
# Directory aliases
alias etf='cd ~/git/PersonalProjects/EmergencyTeamFrontend/'
alias etb='cd ~/git/PersonalProjects/EmergencyTeamBackend/'
alias 3feed='cd ~/git/Defacto/360-Feedback/'
alias 3web='cd ~/git/Defacto/360WebApp/'
alias hours='cd ~/Git/Defacto/Hours'
alias LS='cd ~/git/Defacto/LearningSpaces'
alias proof='cd ~/git/Defacto/proof'

alias shopback='cd ~/git/Hanze/ShopOfTheFuture_backend'
alias shopfront='cd /git/Hanze/ShopOfTheFuture_frontend'
alias shopmob='cd /git/Hanze/ShopOfTheFuture_android'

alias newtab='cd /git/PersonalProjects/new-tab-replacement'
alias poc='cd ~/git/ProofOfConcepts/'
alias resolutions='system_profiler SPDisplaysDataType |grep Resolution'
eval $(thefuck --alias)
# # Preferred editor for local and remote sessions
#if [[ -n $SSH_CONNECTION ]]; then
#  export EDITOR='vim'
#else
  # export EDITOR='vim'
#fi
export EDITOR="vim"

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
# eval "$(rbenv init -)"
# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export FZF_DEFAULT_COMMAND='ag -l -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

#Vim mode in zsh

# bindkey '^P' history-beginning-search-backward
# bindkey '^N' history-beginning-search-forward
# bindkey '^?' backward-delete-char
# bindkey '^h' backward-delete-char
# bindkey '^w' backward-kill-word
# bindkey '^r' history-incremental-search-backward
# bindkey 'jj' vi-cmd-mode

export NVM_DIR="/Users/alexander/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

PS1="$PS1"'$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD")'

export TMPDIR="/private/tmp" # fix vim-dispatch/issues/64
source /usr/local/share/zsh/site-functions/_aws
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# added by travis gem
[ -f /Users/alexander/.travis/travis.sh ] && source /Users/alexander/.travis/travis.sh
